#{
  link(
    "../",
    html.img(
      src: "https://api.iconify.design/lucide:house.svg",
      alt: "homepage",
    ),
  )
  link(
    "https://github.com/adamanteye/blog",
    html.img(
      src: "https://api.iconify.design/lucide:github.svg",
      alt: "repo",
    ),
  )
  link(
    "mailto:adamanteye@disroot.org",
    html.img(
      src: "https://api.iconify.design/lucide:mail-plus.svg",
      alt: "email",
    ),
  )
  link(
    "/atom.xml",
    html.img(
      src: "https://api.iconify.design/lucide:rss.svg",
      alt: "feed",
    ),
  )

  [

    Generated by *typst* and *Makefile*
  ]
}
