#link(
  "https://github.com/adamanteye/blog",
  html.img(
    src: "https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/github.svg",
    alt: "repo",
  ),
)
#link(
  "mailto:adamanteye@disroot.org",
  html.img(
    src: "https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/mailboxdotorg.svg",
    alt: "email",
  ),
)
#link(
  "https://blog.adamanteye.cc/atom.xml",
  html.img(
    src: "https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/rss.svg",
    alt: "feed",
  ),
)

Generated by *Makefile* and *typst*
