#{
  html.html({
    html.head({
      html.title()[Adamanteye's Blog]
      html.meta(
        name: "description",
        content: "",
      )
      include "meta.typ"
      html.link(rel: "stylesheet", href: "./common.css")
    })
    html.body({
      html.header({ include "header.typ" })
      html.main({
        html.nav({ include "src/nav.typ" })
      })
      html.footer([
        #link(
          "./",
        )[Home]
        \/
        #link(
          "https://github.com/adamanteye/blog",
        )[Source]
        \/
        #link(
          "mailto:adamanteye@disroot.org",
        )[Email]
        \/
        #link(
          "./atom.xml",
        )[Feed]

        Generated by *typst* and *Makefile*
      ])
    })
  })
}
