#{
  html.html({
    html.head({
      html.title()[Adamanteye's Blog]
      html.meta(
        name: "description",
        content: "",
      )
      include "meta.typ"
      html.link(rel: "stylesheet", href: "./common.css")
    })
    html.body({
      html.header({
        html.p(class: "header")[Adamanteye's Blog]
        html.nav([
          #link(
            "../",
          )[Home]
          \/
          #link(
            "https://github.com/adamanteye/blog",
          )[Source]
        ])
      })
      html.main({
        html.nav({ include "src/nav.typ" })
      })
      html.footer({
        html.nav([
          #link(
            "./",
          )[Home]
          \/
          #link(
            "https://github.com/adamanteye/blog",
          )[Source]
          \/
          #link(
            "mailto:xuelin@adamanteye.cc",
          )[Email]
          \/
          #link(
            "./atom.xml",
          )[Feed]
        ])

        [Generated by *typst* and *Makefile*]
      })
    })
  })
}
