#{
  html.meta(charset: "utf-8")
  html.meta(
    name: "viewport",
    content: "width=device-width, initial-scale=1.0",
  )
  html.link(rel: "icon", type: "image/webp", href: "/favicon.webp")
  html.link(rel: "dns-prefetch", href: "//cdn.jsdelivr.net")
  html.link(rel: "preconnect", href: "https://cdn.jsdelivr.net")
}

#let footer = [Generated by *typst*, *lilypond* and *Make*]
