#let home = link(
  "../../../",
)[Home]

#let source = link(
  "https://github.com/adamanteye/blog",
)[Source]

#let conf(
  title: str,
  desc: str,
  doc,
) = {
  html.html({
    html.head({
      include "meta.typ"
      html.title()[#title]
      html.meta(
        name: "description",
        content: desc,
      )
      html.link(rel: "stylesheet", href: "../../../common.css")
    })
    html.body({
      html.header({
        html.h1(class: "header")[#title - Adamanteye's Blog]
        html.nav([
          #home
          \/
          #source
        ])
      })
      html.main({
        html.article({
          show math.equation: html.frame
          doc
        })
      })
      html.footer({
        html.nav([
          #home
          \/
          #source
          \/
          #link(
            "mailto:xuelin@adamanteye.cc",
          )[Email]
          \/
          #link(
            "../../../atom.xml",
          )[Feed]
        ])

        [Generated by *typst* and *Makefile*]
      })
    })
  })
}
