#let conf(
  title: str,
  desc: str,
  doc,
) = {
  html.html({
    html.head({
      include "meta.typ"
      html.title()[#title]
      html.meta(
        name: "description",
        content: desc,
      )
      html.link(rel: "stylesheet", href: "../common.css")
    })
    html.body({
      html.header({
        html.h1(class: "header")[#title - Adamanteye's Blog]
        html.nav([
          #link(
            "../",
          )[Home]
          \/
          #link(
            "https://github.com/adamanteye/blog",
          )[Source]
        ])
      })
      html.main({
        html.article({
          doc
        })
      })
      html.footer({
        html.nav([
          #link(
            "../",
          )[Home]
          \/
          #link(
            "https://github.com/adamanteye/blog",
          )[Source]
          \/
          #link(
            "mailto:xuelin@adamanteye.cc",
          )[Email]
          \/
          #link(
            "../atom.xml",
          )[Feed]
        ])

        [Generated by *typst* and *Makefile*]
      })
    })
  })
}
